# Site settings
title: isnoopytokky blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://isnoopytokky.github.io"
twitter_username: isnoopytokky
github_username:  isnoopytokky

# Build settings
markdown: redcarpet
permalink: pretty
